import { test, expect } from "@playwright/test"

test("register", async ({ page }) => {
  await page.goto("http://localhost:3000/auth/register")
  await page.getByPlaceholder("John Doe").click()
  await page.getByPlaceholder("John Doe").fill("Dinuda ")
  await page.getByPlaceholder("john.doe@example.com").click()
  await page.getByPlaceholder("john.doe@example.com").fill("ydinuda@gmail.com")
  await page.getByPlaceholder("******").click()
  await page.getByPlaceholder("******").fill("Dinuda@1")
  await page.getByPlaceholder("******").press("Enter")
})

test("login", async ({ page }) => {
  await page.goto("http://localhost:3000/auth/login")
  await page.getByPlaceholder("john.doe@example.com").click()
  await page.getByPlaceholder("john.doe@example.com").fill("ydinuda@gmail.com")
  await page.getByPlaceholder("******").click()
  await page.getByPlaceholder("******").fill("Dinuda@1")
  await page.getByRole("button", { name: "Login" }).click()
  //   await page.goto("http://localhost:3000/settings")
  await page.getByRole("link", { name: "Server" }).first().click()
  await page.getByRole("link", { name: "Client" }).first().click()
  await page.getByRole("link", { name: "Admin" }).first().click()
  await page
    .locator("div")
    .filter({ hasText: /^Admin-only API RouteClick to test$/ })
    .getByRole("button")
    .click()
  await page
    .locator("div")
    .filter({ hasText: /^Admin-only Server ActionClick to test$/ })
    .getByRole("button")
    .click()
  await page.getByRole("link", { name: "Settings" }).click()
  await page.getByText("SettingsServerClientAdmin Auth SettingsNameEmailNew PasswordConfirm").click()
  await page.getByPlaceholder("Password", { exact: true }).click()
  await page.getByPlaceholder("Password", { exact: true }).fill("Dinuda@123")
  await page.getByPlaceholder("Password", { exact: true }).press("ControlOrMeta+a")
  await page.getByPlaceholder("Password", { exact: true }).press("ControlOrMeta+c")
  await page.getByPlaceholder("Confirm Password").click()
  await page.getByPlaceholder("Confirm Password").fill("Dinuda@123")
  await page.getByRole("button", { name: "Save" }).click()
})
